runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: "2.6.1"
- name: PIL
  version: "1.1.7"

env_variables:
  DJANGO_SETTINGS_MODULE: 'myapp.settings'

# [START handlers]
handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /upload/(.*\.(gif|png|jpg|csv|json))$
  static_files: client/\1
  upload: client/.*\.(gif|png|jpg|csv|csv)$

- url: /.*
  script: main.app
# [END handlers]